config/routes.rb
Rails.application.routes.draw do
  root to: "landing_page#start"

  get :ping, controller: :heartbeat
  get :healthcheck, controller: :heartbeat
  get :sha, controller: :heartbeat

  scope via: :all do
    get "/404", to: "errors#not_found"
    get "/422", to: "errors#unprocessable_entity"
    get "/429", to: "errors#too_many_requests"
    get "/500", to: "errors#internal_server_error"
  end

  get "/sign-in" => "sign_in#index"
  get "/sign-out" => "sign_out#index"
  get "/sign-in/user-not-found", to: "sign_in#new"

  case Env.sign_in_method("dfe-sign-in")
  when "dfe-sign-in"
    get("/auth/dfe/callback" => "sessions#callback")
    get("/auth/dfe/sign-out" => "sessions#signout")
  end
end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController
  skip_before_action :authenticate
  def start
  end
end

app/views/landing_page/start.html.erb
<h1 class="govuk-heading-l"><%= t("service.name") %></h1>

<p class="govuk-body">Use this service to find the details of all initial teacher training (ITT) placement schools.</p>

<h2 class="govuk-heading-m">Who can use this service</h2>

<p class="govuk-body">You can use this service if you are a member of the Department for Education (DfE).</p>

<h2 class="govuk-heading-m">Before you start</h2>

<p class="govuk-body">
  To access this service, you will be asked to sign in or create a DfE Sign-in account.
  DfE Sign-in is how training providers and other education organisations access DfE online services.
</p>

<%= govuk_start_button(text: "Sign in", href: sign_in_path, classes: "govuk-!-margin-top-4") %>